### ISSUE TITLE
Binary 0.5.0 on arm-unknown (RPi 0) appear broken on RPi0W

### ISSUE THREAD

**Issue by baekgaard** [mfreeborn/heliocron#34]
I just installed the binary https://github.com/mfreeborn/heliocron/releases/download/v0.5.0/heliocron-v0.5.0-arm-unknown-linux-gnueabi.tar.gz onto a Raspberry Pi 0 WiFi running Raspbian 10 (buster).

When I call heliocron, it always estimates sunrise and sunset to be at 00:00:00 local time (and hence the day is pretty short).

So something isn't working in that release.

Here is a sample output from the RPi0w (from README.md and works fine on another Linux box I tested on):

```
user@rpi0w:~/heliocron-v0.5.0-arm-unknown-linux-gnueabi $ ./heliocron -d "7 May 2065" -f "%e %B %Y" -l 55.9533N -o 3.1883W report
LOCATION
--------
Latitude: 55.9533N
Longitude: 3.1883W

DATE
----
2065-05-07 12:00:00 +01:00

Solar noon is at:         2065-05-07 00:00:00 +01:00
The day length is:        0h 0m 0s

Sunrise is at:            2065-05-07 00:00:00 +01:00
Sunset is at:             2065-05-07 00:00:00 +01:00

Civil dawn is at:         2065-05-07 00:00:00 +01:00
Civil dusk is at:         2065-05-07 00:00:00 +01:00

Nautical dawn is at:      2065-05-07 00:00:00 +01:00
Nautical dusk is at:      2065-05-07 00:00:00 +01:00

Astronomical dawn is at:  2065-05-07 00:00:00 +01:00
Astronomical dusk is at:  2065-05-07 00:00:00 +01:00

```

I assume something doesn't quite build right on this platform, although I haven't tried to rebuild from source.

**Comment by GorkaMM** [comment]
Exact same thing on my side. Thanks for the help in advance, @mfreeborn

**Comment by mfreeborn** [comment]
Thank you both for flagging this issue - I've managed to take a look at this at last. For reasons that I don't entirely understand, it should all be working now that I've recompiled the RPi 0 binary using a the `arm-unknown-linux-gnueabihf` target triple rather than `arm-unknown-linux-gnueabi`. I can only seem to find conflicting information regarding which one is correct and which one works at all when compiling for the RPi 0. In this case, both seem to run, but only the `hf`-variant is correct.

It works on my end, but it would be reassuring if either of you could retry with the new binary on the release page (still v0.5.0).

**Comment by mfreeborn** [comment]
No further replies received
