### ISSUE TITLE
Not showing proper time when using report function?

### ISSUE THREAD

**Issue by Dark-Sol** [mfreeborn/heliocron#73]
When using `report`, the time is reported as local noon time:
```:~ $ heliocron report
LOCATION
--------
Latitude: 
Longitude: 

DATE
----
2023-08-09 12:00:00 -03:00

Solar noon is at:         2023-08-09 13:19:48 -03:00
The day length is:        14h 20m 16s

Sunrise is at:            2023-08-09 06:09:40 -03:00
Sunset is at:             2023-08-09 20:29:56 -03:00

Civil dawn is at:         2023-08-09 05:37:13 -03:00
Civil dusk is at:         2023-08-09 21:02:23 -03:00

Nautical dawn is at:      2023-08-09 04:56:53 -03:00
Nautical dusk is at:      2023-08-09 21:42:43 -03:00

Astronomical dawn is at:  2023-08-09 04:11:40 -03:00
Astronomical dusk is at:  2023-08-09 22:27:56 -03:00
```

However, when using `poll`, the time is reported is the same as the system time:
```$ heliocron poll
LOCATION
--------
Latitude:  
Longitude: 

DATE
----
2023-08-09 19:00:39 -03:00
Day

Solar elevation: 14.396°
Azimuth angle:   278.083°
```

Is this correct behavior or should `report` also give the system time?

(Note: I've removed my latitude and longitude as that would identify where I am located, but are entered in my config.toml file.)

**Comment by mfreeborn** [comment]
Yes, this is the expected behaviour. `poll` is intended to show the data in real time (each second), whereas `report` had a resolution of one day, normalised to noon local time.
________________________________
From: Dark-Sol ***@***.***>
Sent: Wednesday, August 9, 2023 11:17:52 PM
To: mfreeborn/heliocron ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mfreeborn/heliocron] Not showing proper time when using report function? (Issue #73)


When using report, the time is reported as local noon time:

LOCATION
--------
Latitude:
Longitude:

DATE
----
2023-08-09 12:00:00 -03:00

Solar noon is at:         2023-08-09 13:19:48 -03:00
The day length is:        14h 20m 16s

Sunrise is at:            2023-08-09 06:09:40 -03:00
Sunset is at:             2023-08-09 20:29:56 -03:00

Civil dawn is at:         2023-08-09 05:37:13 -03:00
Civil dusk is at:         2023-08-09 21:02:23 -03:00

Nautical dawn is at:      2023-08-09 04:56:53 -03:00
Nautical dusk is at:      2023-08-09 21:42:43 -03:00

Astronomical dawn is at:  2023-08-09 04:11:40 -03:00
Astronomical dusk is at:  2023-08-09 22:27:56 -03:00


However, when using poll, the time is reported is the same as the system time:

LOCATION
--------
Latitude:
Longitude:

DATE
----
2023-08-09 19:00:39 -03:00
Day

Solar elevation: 14.396°
Azimuth angle:   278.083°


Is this correct behavior or should report also give the system time?

(Note: I've removed my latitude and longitude as that would identify where I am located, but are entered in my config.toml file.)
